### ISSUE TITLE
Miscount in CASE statement

### ISSUE THREAD

**Issue by L3Home** [Loloppe/ChroMapper-AutoMapper#2]
There is a numerical mistake in one of the case/switch statements in one of the files. I was just skimming the code to try to figure out which options to use, and ran across it.

In https://github.com/Loloppe/ChroMapper-AutoMapper/blob/master/Items/Helper.cs the Red UP_LEFT and Blue UP intersection is set to only use 6 options, when there are in fact 7 of them.

Sidenote request: For each option/field in the UI, a tooltip that explains what higher vs lower numbers will do, what "threshold" and "onset" really mean, and that sort of thing, would be greatly appreciated! :) Thanks for your hard work!

**Comment by Loloppe** [comment]
Thanks for letting me know, I've updated the source and the release with the fix.
On-hover or tooltip is just too complicated for me at the moment, so there's no plan for that. The whole UI could use a redesign to be honest and I just hate UI stuff.
