### ISSUE TITLE
Doesn't work on V3

### ISSUE THREAD

**Issue by erktiky** [Loloppe/ChroMapper-AutoMapper#3]
Hello, I have ChroMapper V3 and I've tried using this plugin but it doesn't work. I am putting all the files into the plugins folder, but it won't appear in the loaded plugins section. Also, when I use this plugin, it breaks all of the other plugins; for some reason, there are 0 loaded plugins. When I remove the auto mapper the other plugins start working again.
BTW I downloaded the V3 version

**Comment by Loloppe** [comment]
I need more info. Where did you get your v3 CM build? Also, what error do you get? You can press ~ to open the console.

**Comment by erktiky** [comment]
1. I am currently using the v3 CM with the official launcher (Dev release channel)
![obraz_2023-01-26_190805970](https://user-images.githubusercontent.com/99813394/214914856-73c97a22-1712-4358-8409-1d1aaf3776ce.png)
![image](https://user-images.githubusercontent.com/99813394/214915243-2aba766a-cab1-4d51-89ca-225b91dd73da.png)
2. Error:
![obraz_2023-01-26_190728425](https://user-images.githubusercontent.com/99813394/214914721-75f68ba9-f985-4ea6-b322-b334c040d5e4.png)


![image](https://user-images.githubusercontent.com/99813394/214915500-4c221a78-fa71-4b67-8721-822a05ce249e.png)

**Comment by Loloppe** [comment]
New release should work with it.
