### ISSUE TITLE
How do i even use it lmao

### ISSUE THREAD

**Issue by Zombsloid** [Loloppe/ChroMapper-AutoMapper#8]
im clueless on how to use it... all i found out is where it is. (tab, click auto mapper)
please help

**Comment by Zombsloid** [comment]
also is this like beatsage where it will auto gen blocks? or does it only do lights, and stuff like that

**Comment by terrificobjects** [comment]
Same. This is a significant problem that the author gives no easily found data on using this plugin.

**Comment by IonEwe** [comment]
Select a part of the map (or notes). press tab to open  the side menu, click on Auto Mapper.  select some options with the check boxes. press the [light] "button".  but yeah needs a wiki.

**Comment by Loloppe** [comment]
Not sure how you guys found this plugin without the ChroMapper discord, which has a help channel where you can ask for help with plugins.
This plugin can be used the same way as most other plugins. Download the proper version for your CM, so right now stable CM and latest AutoMapper version. You extract the files in the chromapper/Plugins folder. In CM, open your map, press Tab, this should open a window on the right of the screen. One of the button there is AutoMapper. When you press that button, another window open with all the buttons and options. Most of the details for those are written in the README on the github, but the main thing to know is that the Audio button = Generate notes based on audio, Map button = Generate flow based on current notes, Light button = Generate lights based on current notes. And like IonEwe said, you can select notes if you want, and then press Map or Light to just generate for those notes (or use Audio Range fields to generate a specific timeframe with Audio).
